<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getPaginatedPosts($page, $size = 5){
        $posts = $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:Post p ORDER BY p.id DESC'
        )->getResult();
		
		return array_slice($posts, ($page - 1) * $size, $size);
	}
	
	public function getCount(){
		return $this->getEntityManager()->createQuery(
                'SELECT COUNT(p) FROM AppBundle:Post p'
            )->getSingleScalarResult();
	}
}
