<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getPaginatedPosts($page, $size = 5){
		/*Granice za citanje podataka*/
		$low = ($page - 1) * $size + 1;
		$upp = $page * $size;
		
        return $this->getEntityManager()->createQuery(
                'SELECT p FROM AppBundle:Post p WHERE p.id >= '.$low.' AND p.id <= '.$upp
            )->getResult();
	}
	
	public function getCount(){
		return $this->getEntityManager()->createQuery(
                'SELECT COUNT(p) FROM AppBundle:Post p'
            )->getSingleScalarResult();
	}
}
