<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getCount(){
		return $this->getEntityManager()->createQuery(
                'SELECT COUNT(p) FROM AppBundle:User p'
            )->getSingleScalarResult();
	}
}
