home:
    path:     /
    defaults: { _controller: AppBundle:Page:home }
    methods:  [GET]

page1:
    path: /page/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

page:
    path:     /page/{page}
    defaults: { _controller: AppBundle:Page:home }
    methods:  [GET]

post:
    path:     /post/{id}
    defaults: { _controller: AppBundle:Page:post }
    methods:  [GET, POST]

category_page:
    path:     /category/{page}/{id}
    defaults: { _controller: AppBundle:Page:category }
    methods:  [GET]

category:
    path:     /category/{id}
    defaults: { _controller: AppBundle:Page:category }
    methods:  [GET]

about:
    path:     /about
    defaults: { _controller: AppBundle:Page:about }
    methods:  [GET]

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Page:contact }
    methods:  [GET, POST]



register:
    path:     /register
    defaults: { _controller: AppBundle:Login:register }
    methods:  [GET, POST]

login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }
    methods:  [GET, POST]

logout:
    path:     /logout

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:profile }
    methods:  [GET, POST]

admin_request:
    path:     /admin_request/{id}
    defaults: { _controller: AppBundle:Profile:adminrequest }
    methods:  [GET]

admin:
    path:     /admin/posts
    defaults: { _controller: AppBundle:Admin\Page:admin }
    methods:  [GET]

admin_requests:
    path:     /admin/requests
    defaults: { _controller: AppBundle:Admin\Page:requests }
    methods:  [GET]

admin_grant:
    path:     /admin/requests/grant/{id}/{allow}
    defaults: { _controller: AppBundle:Admin\Grant:admin }
    methods:  [GET]

comments:
    path:     /admin/comments
    defaults: { _controller: AppBundle:Admin\Page:comments }
    methods:  [GET]

comment_moderate:
    path:     /admin/comments/allow/{id}/{allow}
    defaults: { _controller: AppBundle:Admin\Grant:comment }
    methods:  [GET]

admin_categories:
    path:     /admin/categories
    defaults: { _controller: AppBundle:Admin\Page:categories }
    methods:  [GET]

new_post:
    path:     /admin/new_post
    defaults: { _controller: AppBundle:Admin\Insert:post }
    methods:  [GET, POST]

new_category:
    path:     /admin/new_category
    defaults: { _controller: AppBundle:Admin\Insert:category }
    methods:  [GET, POST]