home:
    path:     /
    defaults: { _controller: AppBundle:Page:home }
    methods:  [GET]

page1:
    path: /page/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

page:
    path:     /page/{page}
    defaults: { _controller: AppBundle:Page:home }
    methods:  [GET]

about:
    path:     /about
    defaults: { _controller: AppBundle:Page:about }
    methods:  [GET]

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Page:contact }
    methods:  [GET, POST]